### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pablopilah** [lukasgolson/GO-RNG-Cracker#17]
Hello lukas, how are you? Can you help me with this error?: it happens when I try to run main.go

# awesomeProject/internal/application
..\..\internal\application\initialize.go:31:18: undefined: overlapPerFile
..\..\internal\application\initialize.go:121:2: overlapPerFile declared and not used

**Comment by lukasgolson** [comment]
Hello Pablo,

Looks like I accidentally pushed incomplete code to the master branch. The code should now compile correctly again.

Thanks,

Lukas
